name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ou a branch em que você deseja que o workflow execute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Docker image
        run: |
          docker build -t your_dockerhub_username/educahub-api:latest .

      - name: Push Docker image
        run: |
          docker push your_dockerhub_username/educahub-api:latest
